### PR TITLE
Update setup_opencv.sh to work on Fedora Linux

### PR DESCRIPTION
**Pull request by yuripourre**

### CODE REVIEW

**Comment by yuripourre** [comment]
@googlebot I signed it!

**Comment by jiuqiant** [comment]
Thanks for reporting this. Fixed in our internal code base upstream, and will be pushed to GitHub in the next release.

**Comment by yuripourre** [comment]
Thank you @jiuqiant

**Comment by jiuqiant** [comment]
Merged in https://github.com/google/mediapipe/commit/6abec128edd6d037e1a988605a59957c22f1e967.

**Pull request closed without merging**
