### PR TITLE
mediapipe tasks ios vision add poseLandmarker , and add an ios exampl…

### PR DESCRIPTION
**Pull request by zhuwen15**
mediapipe tasks ios vision add poseLandmarker , and add an ios example of PoseLandmarkerApp

### CODE REVIEW

**Comment by TelOkan** [comment]
Thanks for precious contribution @zhuwen15. It's perfectly working on CPU. I want to work on GPU. When i set delegate type GPU at base option as assign 2. I am getting crash cause of the CVPixelBuffer. How can i fix it ?

Screenshot 2023-09-05 at 09 29 43

Thanks in advance.

**Comment by zhuwen15** [comment]
> Thanks for precious contribution @zhuwen15. It's perfectly working on CPU. I want to work on GPU. When i set delegate type GPU at base option as assign 2. I am getting crash cause of the CVPixelBuffer. How can i fix it ?
> 
> Screenshot 2023-09-05 at 09 29 43
> 
> Thanks in advance.

It worked fine when detecting in liveStream mode, what kind of mode you used? Here is my code. 
        let options = PoseLandmarkerOptions()
        let baseOptions = BaseOptions()
        baseOptions.modelAssetPath = getModelName()
        baseOptions.delegateType = currentDelegate == .cpu ? MPPBaseOptionsDelegateType_Cpu : 
        MPPBaseOptionsDelegateType_Gpu
        options.baseOptions = baseOptions
        options.minPoseDetectionConfidence = minPoseDetectionConfidence
        options.minTrackingConfidence = minPoseTrackingConfidence
        options.minPosePresenceConfidence = minPosePresenceConfidence
        options.runningMode = runningMode
        options.numPoses = numPoses
        if runningMode == .liveStream {
            options.poseLandmarkerLiveStreamDelegate = self
            if liveStreamDelegate == nil {
                throw PoseLandmarkerHelperError.liveStreamModeHasNoDelegate
            }
        }
        do {
            landmarker = try PoseLandmarker(options: options)
        } catch {
            throw PoseLandmarkerHelperError.failedToSetupLandmarker
        }

**Comment by TelOkan** [comment]
Firstly, thanks for support @zhuwen15. I change my code as you, but i see its work on CPU even if  i have set delegateType as GPU.

Screenshot 2023-09-06 at 09 10 49

**Comment by zhuwen15** [comment]
> Firstly, thanks for support @zhuwen15. I am working on LiveStream mode and change my code as you, but i see its work on CPU even if i have set delegateType as GPU. Also its performance output is same with CPU. I think so GPU delegate couldn't set. am I doing something wrong ? Additionally, has GPU support only LiveStream mode ? there is no support at Video or Image running mode ?
> 
> Screenshot 2023-09-06 at 09 10 49

sorry for the mistake, I think I was wrong when set when set gpu accelerator in "mediapipe/tasks/ios/core/utils/sources/MPPBaseOptions+Helpers.mm"  "baseOptionsProto->mutable_acceleration()->mutable_gpu()->set_use_advanced_gpu_api(true);" maybe we should set metal_delegate here, but I'm unavailable to handle it currently.  Or you can learn about MoveNet, it also has pose estimation, and it supports gpu officially.

**Comment by TelOkan** [comment]
okey @zhuwen15. Thanks for suggestion.
Have nice day!

**Comment by zhuwen15** [comment]
> > Firstly, thanks for support @zhuwen15. I am working on LiveStream mode and change my code as you, but i see its work on CPU even if i have set delegateType as GPU. Also its performance output is same with CPU. I think so GPU delegate couldn't set. am I doing something wrong ? Additionally, has GPU support only LiveStream mode ? there is no support at Video or Image running mode ?
> > Screenshot 2023-09-06 at 09 10 49
> 
> / Or you can learn about MoveNet, it also has pose estimation, and it supports gpu officially. image
> 
> "baseOptionsProto->mutable_acceleration()->mutable_gpu()->set_use_advanced_gpu_api(true);" is the correct way to set gpu mode, just need to add "baseOptions.delegateType = self.delegateType;" in the file "mediapipe/tasks/ios/core/sources/MPPBaseOptions.m", but I got the same error image something is wrong in this method: image

@schmidt-sebastian @kuaashish  Hi, iOS Metal as a GPU acceleration  is not supported yet?  I've implemented gpu settings in MPPBaseOptions.m like below,
image
When sending a CVPixelBuffer whose type is  kCVPixelFormatType_32BGRA to be detected by poseLandmarker, "mediapipe/mediapipe/objc/util.cc"  crashed at default return statement coz image_format was  mediapipe::ImageFormat::SRGB not involved in switch cases. 
image

**Comment by zhuwen15** [comment]
https://github.com/google/mediapipe/pull/4771

This pr solved the problem above, but had metal compile warning
image

**Comment by LyonGao** [comment]
@Alex92908 如何在swift中使用poseLandmarker呢，能指导一下吗？谢谢

**Comment by Alex92908** [comment]
> @Alex92908 如何在swift中使用poseLandmarker呢，能指导一下吗？谢谢

@LyonGao 我fork的库删除了，目前官方没提供poseLandmarker的api。我原先的提交包含了这部分代码以及怎样单独打包PoseLandmarkerSDK.framework, swift 中import PoseLandmarkerSDK
        // 初始化
        let options = PoseLandmarkerOptions()
        let baseOptions = BaseOptions()
        baseOptions.modelAssetPath = "Bundle引入模型文件路径"
        baseOptions.delegateType = currentDelegate == .cpu ? MPPBaseOptionsDelegateType_Cpu : MPPBaseOptionsDelegateType_Gpu
        options.baseOptions = baseOptions
        options.minPoseDetectionConfidence = 0.5
        options.minTrackingConfidence = 0.5
        options.minPosePresenceConfidence = 0.5
        options.runningMode = .liveStream
        options.numPoses = 1 // 1-6
        if runningMode == .liveStream {
            options.poseLandmarkerLiveStreamDelegate = self
            if liveStreamDelegate == nil {
                throw xx_error
            }
        }
        do {
            landmarker = try PoseLandmarker(options: options)
        } catch {
            throw throw xx_error
        }
// 调用
func detect(pixelBuffer: CVPixelBuffer) throws {
        guard runningMode == .liveStream else {
            throw PoseLandmarkerHelperError.detectInWrongMode
        }
        let timestampInMilliseconds = Int(Date().timeIntervalSince1970 * 1000)
        guard let visionImage = try? MPImage(pixelBuffer: pixelBuffer) else {
            throw xx_error
        }
        do {
            try landmarker?.detectAsync(image: visionImage, timestampInMilliseconds: timestampInMilliseconds)
        } catch {
            throw xx_error
        }
    }
    // 结果从代理拿到
    func poseLandmarker(_ poseLandmarker: PoseLandmarker, didFinishDetection result: PoseLandmarkerResult?, timestampInMilliseconds: Int, error: Error?) {}

**Comment by LyonGao** [comment]
@Alex92908 谢谢你的回复。我这两天一直在尝试打包iOS的framework，但是都不成功。我是运行mediapipe/tasks/ios/build_ios_framework.sh这个文件：
```
./build_ios_framework.sh
```
报错信息如下：
```
['python3', '/private/var/tmp/_bazel_gaoliying/4965b3a83bc8da908a30c4b3c899fc93/sandbox/darwin-sandbox/11566/execroot/mediapipe/external/ios_opencv_source/opencv-4.5.3/platforms/ios/build_framework.py', 'bazel-out/ios-x86_64-min12.0-applebin_ios-ios_x86_64-opt-ST-0ffd98a67991/bin/external/ios_opencv_source/iphoneos', '--iphoneos_archs', 'arm64', '--framework_name', 'opencv2', '--build_only_specified_archs', '--without', 'dnn', '--without', 'ml', '--without', 'stitching', '--without', 'photo', '--without', 'objdetect', '--without', 'gapi', '--without', 'flann', '--disable', 'PROTOBUF', '--disable-bitcode', '--disable-swift']
Executing: python3 /private/var/tmp/_bazel_gaoliying/4965b3a83bc8da908a30c4b3c899fc93/sandbox/darwin-sandbox/11566/execroot/mediapipe/external/ios_opencv_source/opencv-4.5.3/platforms/ios/build_framework.py bazel-out/ios-x86_64-min12.0-applebin_ios-ios_x86_64-opt-ST-0ffd98a67991/bin/external/ios_opencv_source/iphoneos --iphoneos_archs arm64 --framework_name opencv2 --build_only_specified_archs --without dnn --without ml --without stitching --without photo --without objdetect --without gapi --without flann --disable PROTOBUF --disable-bitcode --disable-swift
Target //mediapipe/tasks/ios:MediaPipeTaskGraphs_library failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /private/var/tmp/_bazel_gaoliying/4965b3a83bc8da908a30c4b3c899fc93/external/ios_opencv_source/BUILD.bazel:85:11 Middleman _middlemen/@ios_Uopencv_Usource_S_S_Copencv-cc_library-compile failed: (Exit 1): bash failed: error executing command (from target @ios_opencv_source//:build_opencv_xcframework) /bin/bash -c ... (remaining 1 argument skipped)
```
请教一下，你是如何打包的呢？

**Comment by Alex92908** [comment]
@LyonGao https://github.com/google/mediapipe/issues/4665，mediapipe/tasks/ios/build_ios_framework.sh是官方打包pod的脚本，你如果需要poseLandmarker，则需要补下poseLandmarker相关代码，然后补充bazel build脚本。（我先前这个pr有写:(）,如果不需要就直接pod 'MediaPipeTasksVision' 就可以了。

**Comment by UpupupDone** [comment]
@Alex92908 我这边执行mediapipe/tasks/ios/build_ios_framework.sh是打包pod的脚本，构建MediaPipeTasksCommon、MediaPipeTasksVision的pod库，也遇到楼上同样的报错：

Target //mediapipe/tasks/ios:MediaPipeTaskGraphs_library failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /private/var/tmp/_bazel_xxx/e4781890efbb113e234cc87a4512eb04/external/ios_opencv_source/BUILD.bazel:85:11 Middleman _middlemen/@ios_Uopencv_Usource_S_S_Copencv-cc_library-compile failed: (Exit 1): bash failed: error executing command (from target @ios_opencv_source//:build_opencv_xcframework) /bin/bash -c ... (remaining 1 argument skipped)

构建脚本是：
export FRAMEWORK_NAME="MediaPipeTasksCommon" && sh mediapipe/tasks/ios/build_ios_framework.sh --verbose_failures

export FRAMEWORK_NAME="MediaPipeTasksVision" && sh mediapipe/tasks/ios/build_ios_framework.sh --verbose_failures

我在mediapipe/tasks/ios/build_ios_framework.sh脚本中看到cmake版本不大于3.24.0说明，尝试把cmake降级到3.24.0以下，依旧包报同样的错误，请问该如何解决。

**Comment by Alex92908** [comment]
@UpupupDone 如果你需要MediaPipeTasksCommon和MediaPipeTasksVision直接pod 'MediaPipeTasksVision'就可以了

**Comment by UpupupDone** [comment]
我们在尝试真是MedoaPipe能力做裁剪和定制化，所以需要自己构建

周清城

来自 Gmail App


Alex ***@***.***>于2023年12月5日 周二18:51写道：

**Comment by Alex92908** [comment]
@UpupupDone 我定制化是通过自己写脚本打包动态库，官方那个是static库，需要pod 管理

**Comment by Alex92908** [comment]
@UpupupDone 我定制化是通过自己写脚本打包动态库，官方那个是static库，需要pod 管理

**Comment by UpupupDone** [comment]
@Alex92908 只要能构建成功，是否静态库、是否通过pod管理，这些关系都不大

**Comment by Alex92908** [comment]
@UpupupDone 我的意思是你用官方的那个脚本去打包static库直接引入工程是用不了的，我先前也打包导入过。至于你编译失败，我当时执行mediapipe/mediapipe/tasks/ios/build_ios_framework.sh是可以成功的。我后面是打包ios_framework，然后导入项目，其中deps 的OpencvFramework的设定为
deps = OBJC_TASK_COMMON_DEPS + CALCULATORS_AND_GRAPHS + select({
        "//third_party:opencv_ios_sim_arm64_source_build": ["@ios_opencv_source//:opencv_xcframework"],
        "//third_party:opencv_ios_arm64_source_build": ["@ios_opencv_source//:opencv_xcframework"],
        "//third_party:opencv_ios_x86_64_source_build": ["@ios_opencv_source//:opencv_xcframework"],
        "//third_party:opencv_ios_sim_fat_source_build": ["@ios_opencv_source//:opencv_xcframework"],
        "//conditions:default": ["@ios_opencv//:OpencvFramework"],
    }),

**Comment by UpupupDone** [comment]
用不了的原因是什么？自己制作pod库也不行？

周清城

来自 Gmail App


Alex ***@***.***>于2023年12月6日 周三22:35写道：

**Comment by Alex92908** [comment]
@UpupupDone 我没试过自己打包pod库，自己打包pod库应该可以，我当时要做的是需要添加poselandmarker，官方没有这部分的iOS代码，我后面单独针对这个做了ios_framework

**Comment by UpupupDone** [comment]
试过单独构建xcframework，制作pod库是OK的，但因为没有编译opencv，集成到工程会报找不在opencv相关的错误。

构建脚本如下：

# 构建 MediaPipeTasksCommon.xcframework

bazel build -c opt mediapipe/tasks/ios:MediaPipeTasksCommon_framework

# 构建 MediaPipeTasksVision.xcframework

bazel build -c opt mediapipe/tasks/ios:MediaPipeTasksVision_framework


关于你上面说的编译opencv相关配置，我改下试试看。

Alex ***@***.***>于2023年12月6日 周三22:42写道：

**Pull request closed without merging**
