### PR TITLE
Is functions are const funtctions in port.h

### PR DESCRIPTION
**Pull request by PeterPocsi**
All the "Is" functions should be const functions (like several other like IsDone).

### CODE REVIEW

**Comment by PeterPocsi** [comment]
@googlebot I fixed it.

**Comment by PeterPocsi** [comment]
@googlebot I fixed it.

**Comment by jiuqiant** [comment]
Thanks for reporting this. Fixed in our internal code base upstream, and will be pushed to GitHub in the next release.

**Comment by jiuqiant** [comment]
Merged in https://github.com/google/mediapipe/commit/6abec128edd6d037e1a988605a59957c22f1e967.

**Pull request closed without merging**
