### PR TITLE
Fix typo in the document [face_detection:Python Solution API]

### PR DESCRIPTION
**Pull request by matsuren**
Thank you for sharing this wonderful library!
I found a typo and an undefined `mp_drawing` in the document which causes me an error.

### CODE REVIEW

**Comment by matsuren** [comment]
@googlebot I signed it!

**Comment by matsuren** [comment]
Oh, I just noticed that typo I modified was the same as #1670. In addition to the typo, I fixed undefined `mp_drawing` in this pull request. 

Thanks,

**Comment by jiuqiant** [comment]
Thanks for reporting this. Fixed in our internal code base upstream, and will be pushed to GitHub in the next release.

**Comment by jiuqiant** [comment]
Fixed in https://github.com/google/mediapipe/commit/a9b643e0f5978425d948050a2228398929733d05.

**Pull request closed without merging**
