### PR TITLE
Removed opencv framework from MPPVisionTaskRunner dependendencies

### PR DESCRIPTION
**Pull request by priankakariatyml**

### CODE REVIEW

**Comment by priankakariatyml** [comment]
@schmidt-sebastian PR to incorporate a change that somehow got reversed during the merge of the Cocoapods bug fixes PR. [This comment ](https://github.com/google/mediapipe/pull/4380#discussion_r1188173872)points to the change in the merged PR.

**Review by schmidt-sebastian — APPROVED** [review]

**Comment by schmidt-sebastian** [comment]
I think this was already merged as part of another PR. Fingers crossed it stays removed.

**Comment by priankakariatyml** [comment]
> I think this was already merged as part of another PR. Fingers crossed it stays removed.

This line got added again through some other PR that was merged later. Raised a new one.
https://github.com/google/mediapipe/pull/4397

**Comment by schmidt-sebastian** [comment]
Sorry this was actually added by a build script. Imported your next PR and updated our build script.

**Pull request merged**
